[build]
command = "echo 'No build command needed'"  # No build command required for Flask
publish = "path/to/your/flask/app/"  # Path to your Flask app directory

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200